# Generated file used for preloading a child image
set(CMAKE_BUILD_TYPE "" CACHE INTERNAL "NCS child image controlled")
set(CMAKE_VERBOSE_MAKEFILE "FALSE" CACHE INTERNAL "NCS child image controlled")
set(BOARD_DIR "C:/ncs/v1.9.1/zephyr/boards/arm/nrf52840dk_nrf52840" CACHE INTERNAL "NCS child image controlled")
set(ZEPHYR_TOOLCHAIN_VARIANT "gnuarmemb" CACHE INTERNAL "NCS child image controlled")
set(GNUARMEMB_TOOLCHAIN_PATH "C:/ncs/v1.9.1/toolchain/opt" CACHE INTERNAL "NCS child image controlled")
set(EXTRA_KCONFIG_TARGETS "menuconfig_ses" CACHE INTERNAL "NCS child image controlled")
set(NCS_TOOLCHAIN_VERSION "1.9.1" CACHE INTERNAL "NCS child image controlled")
set(EXTRA_KCONFIG_TARGET_COMMAND_FOR_menuconfig_ses "C:\ncs\v1.9.1\toolchain\segger_embedded_studio/html/configure_nordic_project_menuconfig.py" CACHE INTERNAL "NCS child image controlled")
set(BOARD nrf52840dk_nrf52840 CACHE INTERNAL "NCS child image controlled")
set(DTC_OVERLAY_FILE C:/ncs/v1.9.1/nrf/modules/mcuboot/usb.overlay CACHE INTERNAL "NCS child image controlled")
set(DTC_OVERLAY_FILE C:/ncs/v1.9.1/nrf/modules/mcuboot/usb.overlay CACHE INTERNAL "NCS child image controlled")
set(OVERLAY_CONFIG C:/ncs/v1.9.1/nrf/subsys/partition_manager/partition_manager_enabled.conf;C:/ncs/v1.9.1/FIT/HKMC_DEMO_CanToUart/main_program/child_image/mcuboot.conf CACHE INTERNAL "NCS child image controlled")
set(DTC_OVERLAY_FILE C:/ncs/v1.9.1/nrf/modules/mcuboot/usb.overlay CACHE INTERNAL "NCS child image controlled")
set(OVERLAY_CONFIG C:/ncs/v1.9.1/nrf/subsys/partition_manager/partition_manager_enabled.conf;C:/ncs/v1.9.1/FIT/HKMC_DEMO_CanToUart/main_program/child_image/mcuboot.conf CACHE INTERNAL "NCS child image controlled")
